name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: npm install

    - run: xcode-select -p
    - run: pod install
      working-directory: ios

      name: Install pod dependencies
    - name: Build iOS (debug)
     # run: "xcodebuild archive -scheme firstapp -project ios/firstapp.xcodeproj -configuration Debug -archivePath ios/ "
      run:  "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath DerivedData -archivePath DerivedData/Archive/firstapp archive"

    - name: "export"
      run: "xcodebuild -exportArchive -archivePath DerivedData/Archive/firstapp.xarchive -exportOptionsPlist Provisioning/*.plist -exportPath DerivedData/ipa"


    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ../../DerivedData/Archive/*.ipa
