name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - run: ls main/ios
   
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: npm install
      working-directory: main
    - run: ls main
    - run: ls main/ios
    - run: xcode-select -p
    - run: pod install
      working-directory: main/ios
      name: Install pod dependencies
    - run: ls main/ios
    - name: Build iOS (debug)
     # run: "xcodebuild archive -scheme firstapp -project ios/firstapp.xcodeproj -configuration Debug -archivePath ios/ "
      working-directory: main/ios
      run:   "xcodebuild -target firstapp.xcodeproj -scheme firstapp -configuration Debug -sdk iphoneos  ONLY_ACTIVE_ARCH=NO"
      
    
