name: iOS
on: [push, pull_request]
env:
  APP_PATH: ios/output/firstapp.app
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: APP cache
      id: app-cache
      
      uses: actions/cache@v2
      with:
        path: ${{ env.APP_PATH }}
        key: test-${{ hashFiles( 'index.js', 'metro.config.js',  'app.json', 'tsconfig.json', 'ios/Podfile', 'ios/Podfile.lock', 'yarn.lock') }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: npm install 
      if: steps.app-cache.outputs.cache-hit != 'true'
      run: yarn 
        

    - name: Install pod dependencies

      if: steps.app-cache.outputs.cache-hit != 'true'
      run: pod install
      working-directory: ios

      
#     - run: |
#         yarn ios
#         mkdir ios/output
#         find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | grep -r Build/Products/Release-iphonesimulator/*.app | xargs -I '{}'  cp -r '{}' ios/output

#     - name: Build iOS (debug)
#       run: "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp clean archive -sdk iphonesimulator -configuration Debug -UseModernBuildSystem=NO -archivePath DerivedData/Archive/firstapp CODE_SIGNING_ALLOWED=NO"
#       run:  "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath DerivedData -archivePath DerivedData/Archive/firstapp archive"

    # - name: Test iOS (debug)
    #   run:  "xcodebuild test -workspace ios/firstapp.xcworkspace -scheme firstapp -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4' "
    
#     - run: ls ios/output
    
#     - run: sudo xcodebuild -license
#     - uses: actions/upload-artifact@v2
#       with:
#         name: my-artifact
#         path: ios/output
