name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: npm install
#     - name: Start the Appium Server
#       run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &
      # Poll for Appium Server to Start
#     - name: Poll for Appium Server to Start
#       run: |
#           until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
#             sleep 5
#           done
    - run: npm run test:e2e:ios
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
          name: e2e-results
          path: __tests__/

#     - run: xcode-select -p
    
#     - run: pod install
#       working-directory: ios
#       name: Install pod dependencies

#     - name: Build iOS (debug)
#       run:  "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath DerivedData -archivePath DerivedData/Archive/firstapp archive TEST_AFTER_BUILD=YES"

#     - run: cp ios/main.jsbundle DerivedData/Archive/firstapp.xcarchive/Products/Applications/firstapp.app/

#     - uses: actions/upload-artifact@v2
#       with:
#         name: my-artifact
#         path: DerivedData/Archive/
    
