name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: npm install
    - run: ls 
    - run: ls ios/
    - run: xcode-select -p
    - run: pod install
      working-directory: ios

      name: Install pod dependencies
    - name: Build iOS (debug)
#       run: "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp clean archive -sdk iphonesimulator -configuration Debug -UseModernBuildSystem=NO -archivePath DerivedData/Archive/firstapp CODE_SIGNING_ALLOWED=NO"
      run:  "xcodebuild -workspace ios/firstapp.xcworkspace -scheme firstapp -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath DerivedData -archivePath DerivedData/Archive/firstapp archive"

    - run: ls DerivedData/Archive/
    
    - name: Copy file
  # You may pin to the exact commit or the version.
  # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: ios/main.jsbundle
        # Target file
        target: DerivedData/Archive/

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: DerivedData/Archive/
