name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
   
    - run: npm install
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies
  
    - name: Build iOS (debug)
      run: "xcodebuild clean build -scheme SDK -project firstapp.xcodeproj -configuration Release -sdk iphoneos -derivedDataPath derived_data ARCHS=arm64 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO"
     # run:  "xcodebuild -target ‘ios/firstapp.xcodeproj’ -scheme ‘firstapp‘ -configuration “Debug” -sdk iphoneos  CONFIGURATION_BUILD_DIR=’ios‘ ONLY_ACTIVE_ARCH=NO"
